### ISSUE TITLE
Mismatch labels of vertical lines in `intro_sts_tfp.ipynb`

### ISSUE THREAD

**Issue by quanhoang-pm** [juanitorduz/website_projects#112]
Dear @juanitorduz, in cell 34 and cell 38 in [your article](https://github.com/juanitorduz/website_projects/blob/master/Python/intro_sts_tfp.ipynb) **Exploring TensorFlow Probability STS Forecasting**, you wrote

```py
ax[i].axvline(x= param_mean + param_std, color=sns_c[3], linestyle='--', label=r'$\mu \pm 2\sigma$')
```
I thought the label should be `r'$\mu \pm \sigma$'` (without number 2) to match the value `param_mean+param_std`. Please let me know if this is the case or I'm missing something here?

By the way, thanks for the article. I've learned a lot just by following your step-by-step code snippets there.

**Comment by juanitorduz** [comment]
Hey! Thanks for reporting this! Indeed, you are right! I will fix it!

**Comment by juanitorduz** [comment]
I updated the notebook in https://github.com/juanitorduz/website_projects/issues/112 . I will update the blog post later today :)
